spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/socialMedia
    username: postgres
    password: Furkan.63
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  port: 8081
